### ISSUE TITLE
Build fail with angular-cli 1.0

### ISSUE THREAD

**Issue by lautarobock** [quentin-ol/angular2-openlayers#58]
I have no problem with angular-cli@beta, but after update to 1.0 I cant bui;d.
Here a repo with a project that reproduce 
https://github.com/lautarobock/angular2-openlayers-bug

```
$ git clone https://github.com/lautarobock/angular2-openlayers-bug.git
$ cd angular2-openlayers-bug
$ npm install
$ ng build

ERROR in C:/Dev/WebDocuments/Field/testWithMap/node_modules/angular2-openlayers/dist/components/map.component.d.ts (1,1): Cannot find type definition file for 'openlayers'.

ERROR in C:/Dev/WebDocuments/Field/testWithMap/node_modules/angular2-openlayers/dist/components/controls/attribution.component.d.ts (1,1): Cannot find type definition file for 'openlayers'.
```
and more, please see in https://github.com/lautarobock/angular2-openlayers-bug/blob/master/README.md

**Comment by lautarobock** [comment]
Responding to myself, 
```
npm install --save @types/openlayers
```

**Comment by quentin-ol** [comment]
'''npm install''' without argument install all dependencies, including those listed as devDependencies. I've looked at '''package.json''' and it does list '''@types/openlayers'''. Weird that you had to manually issue an '''npm install''' command.

**Comment by lautarobock** [comment]
sorry, when I sayd "responding to me" and closing the issue I mean that is solved :)

**Comment by quentin-ol** [comment]
Hey @lautarobock, the thing is the way you solved the issue should not make a difference, actually.
the ```npm install``` command should have installed this package already. The command that you report as solution is redundant, hence my comment.
Anyways, as you said, it's solved, so great! Happy coding with angular2-openlayers!

**Comment by lautarobock** [comment]
hey @quentin-ol doing `npm install angular2-openlayers` should install `openlayers` and `@types/openlayers' too?
not in my case

**Comment by boom235** [comment]
@quentin-ol  I just had the exact same problem. After installing angular2-openlayers via npm I had to install openlayers (not sure if this helped solving the problem) and @types/openlayers. The last install of @types/openlayers definently solved the problem.

**Comment by pieterdb4477** [comment]
This also solves my problem mentioned in #81
